// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace muhtarlik.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505191439_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Muhtar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturmaTarih")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Muhtars");
                });

            modelBuilder.Entity("muhtarlik.Models.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cadde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sokak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TamAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VatandasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VatandasId");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("muhtarlik.Models.Basvuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BasvuruDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("VatandasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VatandasId");

                    b.ToTable("Basvurular");
                });

            modelBuilder.Entity("muhtarlik.Models.Iletisim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VatandasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VatandasId");

                    b.ToTable("Iletisimler");
                });

            modelBuilder.Entity("muhtarlik.Models.Vatandas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("Vatandaslar");
                });

            modelBuilder.Entity("muhtarlik.Models.Adres", b =>
                {
                    b.HasOne("muhtarlik.Models.Vatandas", "Vatandas")
                        .WithMany("Adresler")
                        .HasForeignKey("VatandasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vatandas");
                });

            modelBuilder.Entity("muhtarlik.Models.Basvuru", b =>
                {
                    b.HasOne("muhtarlik.Models.Vatandas", "Vatandas")
                        .WithMany()
                        .HasForeignKey("VatandasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vatandas");
                });

            modelBuilder.Entity("muhtarlik.Models.Iletisim", b =>
                {
                    b.HasOne("muhtarlik.Models.Vatandas", "Vatandas")
                        .WithMany("Iletisimler")
                        .HasForeignKey("VatandasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vatandas");
                });

            modelBuilder.Entity("muhtarlik.Models.Vatandas", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("Iletisimler");
                });
#pragma warning restore 612, 618
        }
    }
}
